// Regenerates src/data/trips.ts from scripts/raw/trip*.json (OSRM route geometries).
// Adds a deterministic synthetic speed/time profile so the demo feels like real GPS telemetry.
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const raw = join(root, "scripts", "raw")

function mulberry32(a: number) {
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const R = 6371
function distKm(a: [number, number], b: [number, number]) {
  const dLat = ((b[1] - a[1]) * Math.PI) / 180
  const dLon = ((b[0] - a[0]) * Math.PI) / 180
  const lat1 = (a[1] * Math.PI) / 180
  const lat2 = (b[1] * Math.PI) / 180
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2
  return 2 * R * Math.asin(Math.sqrt(h))
}

type Meta = {
  id: string
  name: string
  plate: string
  model: string
  startedLabel: string
  seed: number
  maxPoints: number
}

const metas: Meta[] = [
  { id: "TR-2411", name: "Airport pickup", plate: "BA 392 DP", model: "Škoda Octavia", startedLabel: "28 Sep · 08:12", seed: 11, maxPoints: 500 },
  { id: "TR-2412", name: "Customer handover — Trnava", plate: "BA 711 KE", model: "VW Golf", startedLabel: "28 Sep · 09:47", seed: 22, maxPoints: 800 },
  { id: "TR-2413", name: "Vienna airport run", plate: "TT 509 AC", model: "Škoda Superb", startedLabel: "28 Sep · 11:05", seed: 33, maxPoints: 800 },
  { id: "TR-2414", name: "High Tatras transfer", plate: "BA 392 DP", model: "Škoda Octavia", startedLabel: "27 Sep · 06:30", seed: 44, maxPoints: 850 },
]

type Trip = {
  id: string
  name: string
  plate: string
  model: string
  startedLabel: string
  distanceKm: number
  durationSec: number
  avgSpeed: number
  maxSpeed: number
  coords: [number, number][]
  times: number[]
  speeds: number[]
}

const trips: Trip[] = metas.map((meta, i) => {
  const route = JSON.parse(readFileSync(join(raw, `trip${i + 1}.json`), "utf8")).routes[0]
  const all: [number, number][] = route.geometry.coordinates
  const stride = Math.max(1, Math.ceil(all.length / meta.maxPoints))
  const coords = all.filter((_, idx) => idx % stride === 0 || idx === all.length - 1)
  const n = coords.length

  const cum: number[] = [0]
  for (let k = 1; k < n; k++) cum.push(cum[k - 1] + distKm(coords[k - 1], coords[k]))
  const total = cum[n - 1]

  const rnd = mulberry32(meta.seed)
  const nb = 5 + Math.floor(rnd() * 4)
  const breaks: number[] = [0]
  const targets: number[] = [18 + rnd() * 15]
  for (let b = 1; b <= nb; b++) {
    const f = b / nb
    const t = f > 0.92 ? 14 + rnd() * 18 : 45 + rnd() * 85
    breaks.push(f)
    targets.push(t)
  }

  const speeds: number[] = []
  for (let k = 0; k < n; k++) {
    const f = cum[k] / total
    let j = 1
    while (j < breaks.length - 1 && breaks[j] < f) j++
    const u = Math.min(1, Math.max(0, (f - breaks[j - 1]) / (breaks[j] - breaks[j - 1] || 1)))
    const ease = 0.5 - 0.5 * Math.cos(Math.PI * u)
    let v = targets[j - 1] + (targets[j] - targets[j - 1]) * ease + (rnd() - 0.5) * 14
    if (k === 0 || k === n - 1) v = 3 + rnd() * 4
    speeds.push(Math.round(Math.min(138, Math.max(2, v)) * 10) / 10)
  }

  const times: number[] = [0]
  let t = 40 + rnd() * 50
  for (let k = 1; k < n; k++) {
    const d = cum[k] - cum[k - 1]
    const v = Math.max(5, (speeds[k] + speeds[k - 1]) / 2)
    t += (d / v) * 3600 + rnd() * 1.5
    times.push(Math.round(t))
  }

  const r1 = (x: number) => Math.round(x * 10) / 10
  return {
    id: meta.id,
    name: meta.name,
    plate: meta.plate,
    model: meta.model,
    startedLabel: meta.startedLabel,
    distanceKm: r1(total),
    durationSec: Math.round(t),
    avgSpeed: r1(total / (t / 3600)),
    maxSpeed: Math.max(...speeds),
    coords: coords.map(([lng, lat]) => [Math.round(lng * 1e6) / 1e6, Math.round(lat * 1e6) / 1e6]),
    times,
    speeds,
  }
})

const out = `// AUTO-GENERATED by scripts/generate-trips.ts — do not edit by hand.
// Route geometry © OpenStreetMap contributors, routed via OSRM (router.project-osrm.org).
// Speeds/timestamps are synthetic (seeded), standing in for GPS telemetry events.

export type TripData = {
  id: string
  name: string
  plate: string
  model: string
  startedLabel: string
  distanceKm: number
  durationSec: number
  avgSpeed: number
  maxSpeed: number
  coords: [number, number][]
  times: number[]
  speeds: number[]
}

export const trips: TripData[] = ${JSON.stringify(trips)}
`

writeFileSync(join(root, "src", "data", "trips.ts"), out)
for (const t of trips) {
  console.log(`${t.id} ${t.name}: ${t.distanceKm}km, ${Math.round(t.durationSec / 60)}min, ${t.coords.length} pts`)
}
